name: Build dask-mars image

on:
  workflow_dispatch:
    inputs:
      deployment_branch:
        description: 'Deployment branch'
        required: true
        default: 'main'
      build_mode:
        type: choice
        description: Build mode
        options:
        - dev
        - stable
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'
  
jobs:
  build_dask_mars:
    name: Build dask-mars:${{ inputs.image_tag }} from ${{ inputs.build_mode }}
    uses: ecmwf-projects/cads-build-farm/.github/workflows/build-cads-image.yml@build-from-versions-file
    with:
      image_name: dask-mars
      deployment_branch: ${{ inputs.deployment_branch }}
      build_mode: ${{ inputs.build_mode }}
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit
