name: Build dev-explorer image

on:
  workflow_dispatch:
    inputs:
      deployment_branch:
        description: 'Deployment branch'
        required: true
        default: 'main'
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'
  workflow_run:
    workflows:
    - ecmwf-projects/cads-build-farm/build-images.yml
    types: [requested]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to harbor registry
      uses: docker/login-action@v2
      with:
        registry: '${{ secrets.HARBOR_IP }}'
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Create BuildKit Configuration
      run: |
        cat <<EOF > buildkitd.toml
        [registry."${{ secrets.HARBOR_IP }}"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]
        EOF
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
        endpoint: builders
        buildkitd-flags: --debug
        config: buildkitd.toml

    - name: Checkout cads-deployment repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-deployment
        ref: ${{ github.event.inputs.deployment_branch }}
        token: ${{ secrets.CADS_PAT }}
        path: .

    - name: Set env variables from versions file
      if: ${{ github.event.inputs.image_tag != 'latest' }}
      uses: xom9ikk/dotenv@v2
      with:
        path: ./docker/versions
        mode: test
  
    - name: Checkout cads-api-client repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-api-client
        ref: ${{ env.CADS_COMMON }}
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-api-client

    - name: Checkout cads-deployment repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-deployment
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-deployment

    - name: Clone cads-load-tests repo
      uses: actions/checkout@v2
      with:
        repository: ecmwf-projects/cads-load-tests
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-load-tests

    - name: Checkout cads-catalogue repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-catalogue
        ref: ${{ env.CADS_CATALOGUE }}
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-catalogue

    - name: Checkout cacholote repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cacholote
        ref: ${{ env.CACHOLOTE }}
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cacholote

    - name: Clone cads-common repo
      uses: actions/checkout@v2
      with:
        repository: ecmwf-projects/cads-common
        ref: ${{ env.CADS_COMMON }}
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-common

    - name: Checkout cads-extended-profiles repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-extended-profiles
        ref: ${{ env.CADS_EXTENDED_PROFILES }}
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-extended-profiles

    - name: Checkout cads-worker repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-worker
        ref: ${{ env.CADS_WORKER }}
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-worker

    - name: Clone cads-forms-json repo
      uses: actions/checkout@v2
      with:
        repository: ecmwf-projects/cads-forms-json
        ref: cds2-test
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-forms-json

    - name: Clone cads-forms-cim-json repo
      uses: actions/checkout@v2
      with:
        repository: ecmwf-projects/cads-forms-cim-json
        ref: main
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-forms-cim-json

    - name: Clone cads-messages repo
      uses: actions/checkout@v2
      with:
        repository: ecmwf-projects/cads-messages
        ref: cds2-test
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-messages

    - name: Clone cads-licences repo
      uses: actions/checkout@v2
      with:
        repository: ecmwf-projects/cads-licences
        ref: cds2-test
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-licences

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: docker
        push: true
        tags: ${{ secrets.HARBOR_IP }}/cads/dev-explorer:${{ github.event.inputs.image_tag }}
        file: docker/dev-explorer/Dockerfile
