name: Build csw-api image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'
  workflow_run:
    workflows:
    - ecmwf-projects/cads-build-farm/build-images.yml
    types: [requested]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to harbor registry
      uses: docker/login-action@v3
      with:
        registry: '${{ secrets.HARBOR_IP }}'
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Create BuildKit Configuration
      run: |
        cat <<EOF > buildkitd.toml
        [registry."${{ secrets.HARBOR_IP }}"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]
        EOF
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
        endpoint: builders
        buildkitd-flags: --debug
        config: buildkitd.toml

    - name: Checkout pycsw-dynamic repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/pycsw-dynamic
        token: ${{ secrets.CADS_PAT }}
        path: ./pycsw-dynamic
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./pycsw-dynamic
        push: true
        tags: ${{ secrets.HARBOR_IP }}/cads/csw-api:${{ github.event.inputs.image_tag }}
        file: ./pycsw-dynamic/Dockerfile
