name: Build retrieve-api image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'
  workflow_run:
    workflows:
    - ecmwf-projects/cads-build-farm/build-images.yml
    types: [requested]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup harbor ca certificate from secret
      run: |
        ls /etc/docker
        sudo mkdir -p /etc/docker/certs.d/"${{ secrets.HARBOR_IP }}"
        echo "${{ secrets.HARBOR_CERT }}" | sudo tee /etc/docker/certs.d/"${{ secrets.HARBOR_IP }}"/ca.crt >/dev/null
    - name: Copy ca cert
      run: |
        sudo cp /etc/docker/certs.d/"${{ secrets.HARBOR_IP }}"/ca.crt /etc/ssl/certs/ca-certificates.crt
    - name: Login to harbor registry
      uses: docker/login-action@v2
      with:
        registry: '${{ secrets.HARBOR_IP }}'
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Create BuildKit Configuration
      run: |
        cat <<EOF > buildkitd.toml
        [registry."${{ secrets.HARBOR_IP }}"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]
        EOF
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
        endpoint: builders
        buildkitd-flags: --debug
        config: buildkitd.toml

    - name: Checkout cads-deployment repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-deployment
        ref: COPDS-961-add-cads-common
        token: ${{ secrets.CADS_PAT }}
        path: .

    - name: Checkout cacholote repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cacholote
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cacholote

    - name: Checkout cads-catalogue repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-catalogue
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-catalogue

    - name: Clone cads-common repo
      uses: actions/checkout@v2
      with:
        repository: ecmwf-projects/cads-common
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-licences

    - name: Checkout ogc-api-processes-fastapi repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/ogc-api-processes-fastapi
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/ogc-api-processes-fastapi

    - name: Checkout cads-broker repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-broker
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-broker

    - name: Checkout cads-adaptors repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-adaptors
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-adaptors

    - name: Checkout cads-processing-api-service repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-processing-api-service
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-processing-api-service

    - name: Checkout cads-obs-catalogue-manager repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-obs-catalogue-manager
        token: ${{ secrets.CADS_PAT }}
        path: ./docker/cads-obs-catalogue-manager

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: docker
        push: true
        tags: ${{ secrets.HARBOR_IP }}/cads-dev-env/retrieve-api:${{ github.event.inputs.image_tag }}
        file: docker/retrieve-api/Dockerfile
