#
# CIM is splitted in two parts:
# - cads-cim-api
# - cads-cim-ui
#
# We need to build first the cads-cim-api and then the cads-cim-ui
#

name: Build observation manager image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'
  pull_request:
    types: [edited]
jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup harbor ca certificate from secret
      run: |
        ls /etc/docker
        sudo mkdir -p /etc/docker/certs.d/"${{ secrets.HARBOR_IP }}"
        echo "${{ secrets.HARBOR_CERT }}" | sudo tee /etc/docker/certs.d/"${{ secrets.HARBOR_IP }}"/ca.crt >/dev/null
    - name: Copy ca cert
      run: |
        sudo cp /etc/docker/certs.d/"${{ secrets.HARBOR_IP }}"/ca.crt /etc/ssl/certs/ca-certificates.crt
    - name: Login to harbor registry
      uses: docker/login-action@v2
      with:
        registry: "${{ secrets.HARBOR_IP }}"
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Create BuildKit Configuration
      run: |
        cat <<EOF > buildkitd.toml
        [registry."${{ secrets.HARBOR_IP }}"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]
        EOF
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
        endpoint: builders
        buildkitd-flags: --debug
        config: buildkitd.toml

    - name: Checkout cads-obs-catalogue-manager repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-obs-catalogue-manager
        token: ${{ secrets.CADS_PAT }}
        path: cads-obs-catalogue-manager
        submodules: recursive

    - name: Build and push
      uses: docker/build-push-action@v3

      with:
        context: cads-obs-catalogue-manager
        push: true
        tags: ${{ secrets.HARBOR_IP }}/cads-dev-env/cads-obs-catalogue-manager:latest
        file: cads-obs-catalogue-manager/docker/Dockerfile
