#
# CIM is splitted in two parts:
# - cads-cim-api
# - cads-cim-ui
#
# We need to build first the cads-cim-api and then the cads-cim-ui
#

name: Build cim-ui image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to harbor registry
      uses: docker/login-action@v2
      with:
        registry: "${{ secrets.HARBOR_IP }}"
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Create BuildKit Configuration
      run: |
        cat <<EOF > buildkitd.toml
        [registry."${{ secrets.HARBOR_IP }}"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]
        EOF
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
        endpoint: builders
        buildkitd-flags: --debug
        config: buildkitd.toml

    - name: Checkout cads-cim-api repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-cim-api
        token: ${{ secrets.CADS_PAT }}
        path: cads-cim-api

    - name: Checkout cads-cim-ui repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf-projects/cads-cim-ui
        token: ${{ secrets.CADS_PAT }}
        path: cads-cim-ui

    - name: Build API and push
      uses: docker/build-push-action@v3

      with:
        context: cads-cim-api
        push: true
        tags: ${{ secrets.HARBOR_IP }}/cads/cads-backoffice-deployment/cads-cim-api:latest # We always push the latest tag for the backend
        file: cads-cim-api/Dockerfile

    - name: Build UI and push
      uses: docker/build-push-action@v3

      with:
        context: cads-cim-ui
        push: true
        pull: true # We need to pull the backend image to build the frontend
        tags: ${{ secrets.HARBOR_IP }}/cads/cads-backoffice-deployment/cads-cim-ui:${{ github.event.inputs.image_tag }}
        file: cads-cim-ui/Dockerfile
