name: Build broker image

on:
  workflow_dispatch:
    inputs:
      deployment_branch:
        description: 'Deployment branch'
        required: true
        default: 'main'
      build_mode:
        type: choice
        description: Build mode
        options:
        - dev
        - stable
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  build_broker:
    name: Build broker:${{ github.event.inputs.image_tag }} from ${{ github.event.inputs.build_mode }}
    uses: ecmwf-projects/cads-build-farm/.github/workflows/build-cads-image.yml@build-from-versions-file
    with:
      image: "broker"
      deployment_branch: ${{ github.event.inputs.deployment_branch }}
      build_mode: ${{ github.event.inputs.build_mode }}
      image_tag: ${{ github.event.inputs.image_tag }}
    secrets: inherit
